"""PDF report generation for professional security assessments.

Generates client-ready PDF reports with CVSS/CWE/OWASP LLM/MITRE ATLAS mappings.

Dependencies:
    reportlab>=4.0.0
    pillow>=10.0.0
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any

try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import (
        PageBreak,
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    HAVE_REPORTLAB = True
except ImportError:
    HAVE_REPORTLAB = False
    # Stub types for when reportlab is not available
    colors = None
    letter = None
    ParagraphStyle = None
    getSampleStyleSheet = None
    inch = None
    PageBreak = None
    Paragraph = None
    SimpleDocTemplate = None
    Spacer = None
    Table = None
    TableStyle = None

from aipop.reporters.cvss_cwe_taxonomy import VulnerabilityClassifier


class PDFReportGenerator:
    """Generate professional PDF reports for security assessments.

    Example:
        >>> pdf = PDFReportGenerator("report.pdf")
        >>> pdf.add_title_page("Security Assessment", "Acme Corp")
        >>> pdf.add_executive_summary("Summary text...", metrics)
        >>> pdf.add_findings_section(findings)
        >>> pdf.generate()
    """

    def __init__(self, output_path: str) -> None:
        if not HAVE_REPORTLAB:
            raise ImportError(
                "PDF generation requires reportlab. " "Install with: pip install reportlab pillow"
            )
        """Initialize PDF generator.
        
        Args:
            output_path: Path for output PDF file
        """
        self.output_path = Path(output_path)
        self.output_path.parent.mkdir(parents=True, exist_ok=True)

        self.doc = SimpleDocTemplate(
            str(self.output_path),
            pagesize=letter,
            rightMargin=0.75 * inch,
            leftMargin=0.75 * inch,
            topMargin=0.75 * inch,
            bottomMargin=0.75 * inch,
        )
        self.styles = getSampleStyleSheet()
        self.elements: list[Any] = []
        self.classifier = VulnerabilityClassifier()

        # Create custom styles
        self._setup_custom_styles()

    def _setup_custom_styles(self) -> None:
        """Setup custom paragraph styles."""
        # Title page style
        self.styles.add(
            ParagraphStyle(
                name="TitlePage",
                parent=self.styles["Heading1"],
                fontSize=32,
                textColor=colors.HexColor("#1e3a8a"),
                spaceAfter=30,
                alignment=1,  # Center
                fontName="Helvetica-Bold",
            )
        )

        # Subtitle style
        self.styles.add(
            ParagraphStyle(
                name="Subtitle",
                parent=self.styles["Normal"],
                fontSize=18,
                textColor=colors.HexColor("#3b82f6"),
                spaceAfter=20,
                alignment=1,  # Center
            )
        )

        # Finding title style
        self.styles.add(
            ParagraphStyle(
                name="FindingTitle",
                parent=self.styles["Heading2"],
                fontSize=14,
                textColor=colors.HexColor("#dc2626"),
                spaceAfter=10,
                spaceBefore=20,
            )
        )

    def add_title_page(
        self,
        title: str,
        engagement_name: str,
        date: str | None = None,
    ) -> None:
        """Add professional title page.

        Args:
            title: Report title
            engagement_name: Name of engagement/assessment
            date: Date string (defaults to today)
        """
        if date is None:
            date = datetime.now().strftime("%B %d, %Y")

        self.elements.append(Spacer(1, 2 * inch))
        self.elements.append(Paragraph(title, self.styles["TitlePage"]))
        self.elements.append(Spacer(1, 0.5 * inch))
        self.elements.append(Paragraph(engagement_name, self.styles["Subtitle"]))
        self.elements.append(Spacer(1, 0.3 * inch))
        self.elements.append(Paragraph(date, self.styles["Normal"]))
        self.elements.append(Spacer(1, 0.5 * inch))
        self.elements.append(Paragraph("Generated by AI Purple Ops", self.styles["Normal"]))
        self.elements.append(PageBreak())

    def add_executive_summary(
        self,
        summary_text: str,
        metrics: dict[str, Any],
    ) -> None:
        """Add executive summary section.

        Args:
            summary_text: Summary text paragraph
            metrics: Dictionary of metrics (total_tests, vulnerabilities, etc.)
        """
        self.elements.append(Paragraph("Executive Summary", self.styles["Heading1"]))
        self.elements.append(Spacer(1, 0.2 * inch))
        self.elements.append(Paragraph(summary_text, self.styles["Normal"]))
        self.elements.append(Spacer(1, 0.3 * inch))

        # Metrics table
        data = [
            ["Metric", "Value"],
            ["Total Tests", str(metrics.get("total_tests", 0))],
            ["Vulnerabilities Found", str(metrics.get("vulnerabilities", 0))],
            ["Critical", str(metrics.get("critical", 0))],
            ["High", str(metrics.get("high", 0))],
            ["Medium", str(metrics.get("medium", 0))],
            ["Low", str(metrics.get("low", 0))],
        ]

        table = Table(data, colWidths=[3 * inch, 2 * inch])
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.grey),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                    ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, 0), 12),
                    ("BOTTOMPADDING", (0, 0), (-1, 0), 12),
                    ("BACKGROUND", (0, 1), (-1, -1), colors.beige),
                    ("GRID", (0, 0), (-1, -1), 1, colors.black),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ]
            )
        )

        self.elements.append(table)
        self.elements.append(PageBreak())

    def add_findings_section(self, findings: list[dict[str, Any]]) -> None:
        """Add detailed findings with CVSS/CWE.

        Args:
            findings: List of finding dictionaries with keys:
                - title: Finding title
                - type: Vulnerability type (e.g., "prompt_injection")
                - description: Detailed description
                - impact: Impact description
                - recommendation: Remediation recommendation
        """
        self.elements.append(Paragraph("Detailed Findings", self.styles["Heading1"]))
        self.elements.append(Spacer(1, 0.2 * inch))

        if not findings:
            self.elements.append(
                Paragraph(
                    "No vulnerabilities were identified during this assessment.",
                    self.styles["Normal"],
                )
            )
            return

        for i, finding in enumerate(findings, 1):
            # Get taxonomy classification
            vuln_type = finding.get("type", "unknown")
            taxonomy = self.classifier.classify(vuln_type)
            cvss = taxonomy["cvss"]

            # Finding title
            self.elements.append(
                Paragraph(f"Finding {i}: {finding['title']}", self.styles["FindingTitle"])
            )
            self.elements.append(Spacer(1, 0.1 * inch))

            # CVSS/CWE metadata table
            metadata_data = [
                ["Severity", taxonomy["severity"].value.upper()],
                ["CVSS Score", f"{cvss.base_score} ({cvss.vector_string})"],
                ["CWE", f"{taxonomy['cwe_id']} - {taxonomy['cwe_name']}"],
                ["OWASP LLM", taxonomy["owasp_llm"]],
                ["MITRE ATLAS", taxonomy["mitre_atlas"]],
            ]

            metadata_table = Table(metadata_data, colWidths=[1.5 * inch, 4.5 * inch])
            metadata_table.setStyle(
                TableStyle(
                    [
                        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                        ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
                        ("FONTSIZE", (0, 0), (-1, -1), 9),
                    ]
                )
            )

            self.elements.append(metadata_table)
            self.elements.append(Spacer(1, 0.2 * inch))

            # Description
            self.elements.append(Paragraph("<b>Description:</b>", self.styles["Normal"]))
            self.elements.append(
                Paragraph(
                    finding.get("description", "No description provided."), self.styles["Normal"]
                )
            )
            self.elements.append(Spacer(1, 0.1 * inch))

            # Impact
            self.elements.append(Paragraph("<b>Impact:</b>", self.styles["Normal"]))
            self.elements.append(
                Paragraph(
                    finding.get("impact", "See CVSS score for impact assessment."),
                    self.styles["Normal"],
                )
            )
            self.elements.append(Spacer(1, 0.1 * inch))

            # Recommendation
            self.elements.append(Paragraph("<b>Recommendation:</b>", self.styles["Normal"]))
            self.elements.append(
                Paragraph(
                    finding.get(
                        "recommendation",
                        "Implement security controls to mitigate this vulnerability.",
                    ),
                    self.styles["Normal"],
                )
            )
            self.elements.append(Spacer(1, 0.3 * inch))

            # Page break after every 2 findings to avoid crowding
            if i % 2 == 0 and i < len(findings):
                self.elements.append(PageBreak())

    def generate(self) -> Path:
        """Generate the PDF file.

        Returns:
            Path to generated PDF file
        """
        self.doc.build(self.elements)
        return self.output_path


def generate_report_from_json(
    json_report_path: str,
    output_pdf_path: str,
) -> str:
    """Convert JSON report to PDF.

    Args:
        json_report_path: Path to JSON report file
        output_pdf_path: Path for output PDF file

    Returns:
        Path to generated PDF file
    """
    with open(json_report_path) as f:
        data = json.load(f)

    pdf = PDFReportGenerator(output_pdf_path)

    # Title page
    pdf.add_title_page(
        title="AI Security Assessment Report",
        engagement_name=data.get("engagement_name", "Security Assessment"),
        date=data.get("date", None),
    )

    # Executive summary
    summary_text = data.get(
        "executive_summary",
        "This report documents security vulnerabilities identified during "
        "automated testing of AI/LLM systems.",
    )

    metrics = {
        "total_tests": data.get("total_tests", 0),
        "vulnerabilities": data.get("vulnerabilities_found", 0),
        "critical": data.get("critical_count", 0),
        "high": data.get("high_count", 0),
        "medium": data.get("medium_count", 0),
        "low": data.get("low_count", 0),
    }
    pdf.add_executive_summary(summary_text, metrics)

    # Findings
    findings = data.get("findings", [])
    pdf.add_findings_section(findings)

    # Generate
    output_path = pdf.generate()

    return str(output_path)
